POST https://node-learning-ts9k.onrender.com/videos
Content-Type: application/json

{
    "title": "node video 2",
    "description": "Esse é o primeiro vídeo", 
    "duration": 180
}

###

GET https://node-learning-ts9k.onrender.com/videos

###

PUT https://node-learning-ts9k.onrender.com/videos/e355003c-8ece-4778-b664-b6040fbf5932
Content-Type: application/json

{
    "title": "Video 05",
    "description": "Esse é o terceiro vídeo", 
    "duration": 180
}

###

DELETE https://node-learning-ts9k.onrender.com/videos/0f142f3c-c274-4457-8e6f-40eae79efa3f